### ISSUE TITLE
代码仓库问题

### ISSUE THREAD

**Issue by shawdongGithub** [aliyun/darabonba#129]
1、自己本地写了一个dara模块，本地dara模块怎么相互调用，且本地dara模块的调用不应该涉及到远程仓库。
2、dara install的时候会在当前的dara模块下建立仓库，但是本地有多个dara模块要引用多个同一个远程dara仓库的时候就会重复下载。导致在每个dara模块下都有各自的仓库，非常不符合用户使用习惯，希望能设置一个本地仓库，dara模模块引用的时候先扫描本地仓库，在扫描远程仓库。解决在本地多个dara模块相互调用的问题。

**Comment by JacksonTian** [comment]
可以在 libraries 目录下按远程模块一样，建立软链接来使用。
