### ISSUE TITLE
请问：请求返回是一个list<对象>的时候，怎么解析

### ISSUE THREAD

**Issue by ZJWChrisBond** [aliyun/darabonba#61]
__response.body   是一个list<对象>的stream ，怎么解析成一个list<对象>的数组返回

**Comment by JacksonTian** [comment]
__response.body 本身是个 readable。先 parse 成 any，再 assertAsList 。

**Comment by ZJWChrisBond** [comment]
最新版的Util可以直接解析： var arr = Util.readAsJSON(__response.body);
