### ISSUE TITLE
钉钉群二维码已经过期

### ISSUE THREAD

**Issue by Jzow** [aliyun/darabonba#87]
最近尝试用语雀SDK进行开发，但是语雀没有Java相关的SDK，只有Node.JS/Go/Python的SDK Demo，在同学的介绍下，认识到阿里有的darabonba，刚好能解决我的问题，所以想进一步调研和交流，发现二维码已经过期

**Comment by kiwiflydream** [comment]
+1

**Comment by peze** [comment]
好的 马上更新一下
