### ISSUE TITLE
dara publish 注释问题

### ISSUE THREAD

**Issue by yhydev** [aliyun/darabonba#96]
使用：`dara publish` 时候报错，原因是dara 文件中的多行注释导致的。

main.dara
```
type @organization = string

// 定义一个 model
model User {
  name: string,
  age: number
}

/**
 * 模块的初始化函数
 * @param organization 
 */
init(organization: string) {
  @organization = organization;
}

/**
 * 模块的静态方法
 * @param username 
 * @param age
 */
static function getUser(username: string, age: number): string {
  var user = new User{
    name = username,
    age = age
  };
  return `user's name is ${user.name} ,user's age is ${user.age}! `;
} 

```

报错原因：
![1633881542(1)](https://user-images.githubusercontent.com/31916483/136703819-15a35dfb-2137-4299-8d5f-bef3fcfcd15e.png)

**Comment by peze** [comment]
这个 @param 符号默认是要解析的，所以造成了解析出错
建议直接这样写
`@param` username the name of user

**Comment by yhydev** [comment]
> 这个 @param 符号默认是要解析的，所以造成了解析出错 建议直接这样写 `@param` username the name of user

不太明白你的意思？

**Comment by JacksonTian** [comment]
就是这样设计的。 @param ”param name“ “param description”
